services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db


  backend:
    build: ./backend
    container_name: todo-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/todo

  frontend:
    build:
      context: ./frontend
    container_name: todo-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BASE_URL=http://localhost:3000
    depends_on:
      - backend
    

volumes:
  mongo-data:


